
package com.ejs;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Service", targetNamespace = "http://ejs.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Service {


    /**
     * 
     * @return
     *     returns java.util.List<com.ejs.Bicicleta>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBicicletas", targetNamespace = "http://ejs.com/", className = "com.ejs.GetBicicletas")
    @ResponseWrapper(localName = "getBicicletasResponse", targetNamespace = "http://ejs.com/", className = "com.ejs.GetBicicletasResponse")
    @Action(input = "http://ejs.com/Service/getBicicletasRequest", output = "http://ejs.com/Service/getBicicletasResponse")
    public List<Bicicleta> getBicicletas();

    /**
     * 
     * @return
     *     returns com.ejs.Bicicleta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBicicleta", targetNamespace = "http://ejs.com/", className = "com.ejs.GetBicicleta")
    @ResponseWrapper(localName = "getBicicletaResponse", targetNamespace = "http://ejs.com/", className = "com.ejs.GetBicicletaResponse")
    @Action(input = "http://ejs.com/Service/getBicicletaRequest", output = "http://ejs.com/Service/getBicicletaResponse")
    public Bicicleta getBicicleta();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBicicletasXML", targetNamespace = "http://ejs.com/", className = "com.ejs.GetBicicletasXML")
    @ResponseWrapper(localName = "getBicicletasXMLResponse", targetNamespace = "http://ejs.com/", className = "com.ejs.GetBicicletasXMLResponse")
    @Action(input = "http://ejs.com/Service/getBicicletasXMLRequest", output = "http://ejs.com/Service/getBicicletasXMLResponse")
    public String getBicicletasXML();

}
