
package com.ejs.soapws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BicicletasWebService", targetNamespace = "http://soapWs.ejs.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BicicletasWebService {


    /**
     * 
     * @return
     *     returns com.ejs.soapws.Bicicleta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBicicleta", targetNamespace = "http://soapWs.ejs.com/", className = "com.ejs.soapws.GetBicicleta")
    @ResponseWrapper(localName = "getBicicletaResponse", targetNamespace = "http://soapWs.ejs.com/", className = "com.ejs.soapws.GetBicicletaResponse")
    @Action(input = "http://soapWs.ejs.com/BicicletasWebService/getBicicletaRequest", output = "http://soapWs.ejs.com/BicicletasWebService/getBicicletaResponse")
    public Bicicleta getBicicleta();

    /**
     * 
     * @return
     *     returns java.util.List<com.ejs.soapws.Bicicleta>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBicicletas", targetNamespace = "http://soapWs.ejs.com/", className = "com.ejs.soapws.GetBicicletas")
    @ResponseWrapper(localName = "getBicicletasResponse", targetNamespace = "http://soapWs.ejs.com/", className = "com.ejs.soapws.GetBicicletasResponse")
    @Action(input = "http://soapWs.ejs.com/BicicletasWebService/getBicicletasRequest", output = "http://soapWs.ejs.com/BicicletasWebService/getBicicletasResponse")
    public List<Bicicleta> getBicicletas();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBicicletasXML", targetNamespace = "http://soapWs.ejs.com/", className = "com.ejs.soapws.GetBicicletasXML")
    @ResponseWrapper(localName = "getBicicletasXMLResponse", targetNamespace = "http://soapWs.ejs.com/", className = "com.ejs.soapws.GetBicicletasXMLResponse")
    @Action(input = "http://soapWs.ejs.com/BicicletasWebService/getBicicletasXMLRequest", output = "http://soapWs.ejs.com/BicicletasWebService/getBicicletasXMLResponse")
    public String getBicicletasXML();

}
